question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Brezhnev was the 5th leader of the USSR.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "Antarctica is the largest desert in the world.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                       "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                       "question": "The United States of America was the first country to launch a man into space.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "An isosceles triangle has two sides of equal length as opposed to three.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Sports", "type": "boolean", "difficulty": "medium",
                                       "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
